### ISSUE TITLE
Ayo.js Core Team meeting 2017-10-13

### ISSUE THREAD

**Issue by ghost** [ayojs/ayo#105]
## Time

21:00 (9:00pm) UTC, Friday the 13th October 2017. Convert to your local time [here](https://www.timeanddate.com/worldclock/fixedtime.html?msg=Ayo.js+Core+Team+meeting+2017-10-13&iso=20171013T21&p1=135)!

## Invited

- @addaleax (Core team)
- @aqrln (Core team)
- @pup (Core team)
- @Qard (Core team)
- @sandfox (Core team)
- @TimothyGu (Core team)
- @varjmes (Core team)

_Additionally, any member of the Ayo.js moderation team is welcome to participate._

## Agenda

_If you have points or issues you want to see discussed in this meeting, please comment down below!_

Issues labelled with the `core_meeting_agenda` label will be added to the agenda.

## Joining the meeting

For the invited, a private link to join the meeting as a participant will be provided. _TODO: how to view the meeting as a non-participant?_

**Comment by ghost** [comment]
closes #90

**Comment by ghost** [comment]
the meeting is concluded! we'll hopefully have a recording up by next week!

**Comment by TimothyGu** [comment]
I'm so sorry to have missed the meeting! The time zone thing was getting to me real hard...
