### ISSUE TITLE
Meta: Issue / PR Labels

### ISSUE THREAD

**Issue by sandfox** [ayojs/ayo#11]
Do we want to copy across all/some/none the issue/PR labels that exist on upstream for use here?

More than happy to volunteer for the task.

**Comment by addaleax** [comment]
I don’t think all of them make sense (like, we’re never going to get AIX support or something like), but for most, yes. Esp. the ones concerning specific parts of Node, like the ones for individual core modules…

**Comment by addaleax** [comment]
Things that make sense imho:
- addons
- assert
- async_hooks
- async_wrap
- benchmark
- blocked
- buffer
- build
- c++
- cares
- child_process
- CI / flaky test
- cli
- cluster
- confirmed-bug
- console
- crypto
- dgram
- dns
- doc
- domain
- duplicate
- embedding
- encoding
- errors
- events
- feature requested
- fs
- good first contribution
- help wanted
- http_parser
- http
- https
- http2
- in progress
- inspector
- install
- intl
- invalid
- macos
- memory
- mentor-available
- meta
- module
- n-api
- net
- notable change
- npm
- openssl
- os
- path
- performance
- post-mortem
- process
- promises
- punycode
- python
- querystring
- question
- readline
- regression
- repl
- security
- semver-major
- semver-minor
- stalled
- stream
- string_decoder
- test
- timers
- tls
- tools
- tracing
- tty
- url-whatwg
- url
- util
- V8 engine
- vm
- windows
- wontfix
- zlib

Things that make no sense for now:
- aix
- arm
- backporting/LTS labels (we don’t even have releases yet?)
- code-and-learn
- ctc-agenda
- ctc-review
- debugger
- diag-agenda
- freebsd
- known limitation
- mips
- ppc
- refactor to ES6+
- s390
- smartos
- Windows Subsystem for Linux (WSL)

(Some of these are just labels where I personally don’t see the point, i.e. I think they are used for labelling as a purpose on its own)

Everyone, feel free to edit the list as you like :)

**Comment by varjmes** [comment]
As someone who has vastly more intimate knowledge about this than I, I am happy for you to take the lead on this @addaleax

**Comment by Fishrock123** [comment]
As large of a list as it is, I agree those look good.

Note that most of those refer to Node.js subsystems. Here is the list without those:


- blocked
- c++
- CI / flaky test
- confirmed-bug
- duplicate
- embedding
- feature requested
- good first contribution
- help wanted
- in progress
- invalid
- macos
- memory
- mentor-available
- meta
- notable change
- performance
- post-mortem
- promises
- python
- question
- regression
- security
- semver-major
- semver-minor
- stalled
- tracing
- windows
- wontfix

And the following are about dependencies:
- cares
- V8 engine
- npm
- openssl
- http_parser

Of note, a `libuv` label is missing.

**Comment by addaleax** [comment]
Done! We can refine later.

**Comment by addaleax** [comment]
Also, `libuv` was an oversight :)
