### ISSUE TITLE
have an at least temporary place for chat discussion

### ISSUE THREAD

**Issue by Fishrock123** [ayojs/ayo#12]
It'd probably be useful to have an irc / slack channel (or anything else less asynchronous than github) for coordination.

At the very least, it would seem useful to me, as it was useful to io.js.

**Comment by varjmes** [comment]
I agree completely, trying to communicate with folk (like letting repo members know that we've added temporary restrictions) has been difficult.

**Comment by zkat** [comment]
I'm more than happy to have a channel dedicated to this in wealljs, or we can spin up a new discord

**Comment by ghost** [comment]
discord sounds fine to me as long as it's temporary, i don't think everyone in the org is in wealljs

**Comment by varjmes** [comment]
I'd like to keep this out of wealljs. Discord sounds perfect.

**Comment by zkat** [comment]
https://discord.gg/Q6WJdHv I've created a discord.

**Comment by hypesystem** [comment]
Should this maybe be promoted more visibly (like in the README)? (Then the issue could be closed, too.)

**Comment by varjmes** [comment]
@hypesystem I believe that's the plan but we're going to wait a few days :)

**Comment by ghost** [comment]
It is would be great to have slack channel. Plus slack badge in readme powered by Slackin :)

**Comment by ljharb** [comment]
i definitely prefer slack over discord

**Comment by grahamperrin** [comment]
FWIW I prefer Matrix ([clients](https://matrix.org/docs/projects/try-matrix-now.html)). In any case, I joined the room at Discord. 

Thanks 👍

**Comment by varjmes** [comment]
Slack requires payment if we want to keep history and things like that. People seem to be happy with Discord as it stands and has been very successful for the http://package.community community, too :)

**Comment by equinox** [comment]
@varjmes For what it's worth, Matrix doesn't require payment of any kind, and has configurable history settings for rooms.

Matrix also bridges to various IRC networks and other services like gitter, etc.

**Comment by varjmes** [comment]
I feel like Discord has won here for the time being, but if it becomes less than suitable, please open an issue and we can revisit.
