### ISSUE TITLE
Discord invite has expired

### ISSUE THREAD

**Issue by emma-sg** [ayojs/ayo#123]
Sorry for not following the issue template, just wanted to inform you that the discord invite link doesn't seem to be working (it says it's expired).

Thanks!
E

**Comment by ghost** [comment]
are you using the one in the readme? i.e. this one: https://discord.gg/hCgptwH

**Comment by emma-sg** [comment]
Yes, that's the same one.

**Comment by emma-sg** [comment]
Was my (and Discord's to an extent) fault, I had reached the max number of servers. Discord didn't indicate anything like that though... Anyways, all good!
