### ISSUE TITLE
what is the rationale for this project..

### ISSUE THREAD

**Issue by aschrijver** [ayojs/ayo#126]
hi,

interesting project.. maybe :)
but since ayojs.tech is not up yet:

i like the _for humans_ in the tagline, but what are some of the usp's of this project?
why are you better than nodejs?

thanks

**Comment by benjamingr** [comment]
Please see https://github.com/ayojs/ayo/issues/125 , this sort of issue gets opened quite often. 

The goal isn't to be "better" than Node.js objectively, it's to provide an alternative with different focus points and to see how that sort of collaboration works. Many of the people involved in Ayo are involved in Node.js and the two are not exclusive.

**Comment by aschrijver** [comment]
thanks @benjamingr

interesting.. i'll keep following you :)
