### ISSUE TITLE
{ Title Removed }

### ISSUE THREAD

**Issue by w0rp** [ayojs/ayo#20]
_Edit: Friday 25th August, 2017. 11:10am (GMT + 1)_

This comment was removed due to its inflammatory content.

-- @varjmes

**Comment by pup** [comment]
we forked node because we don't agree with the longstanding

**Comment by TimothyGu** [comment]
That's how open source works, my friend. Note that there are more than 7k forks of Node.js as documented by GitHub.

**Comment by varjmes** [comment]
I edited the issue title and content as they were not constructive.
