### ISSUE TITLE
If you support ES modules, you can beat node

### ISSUE THREAD

**Issue by SteveCruise** [ayojs/ayo#21]
Please do it!

**Comment by TimothyGu** [comment]
Node.js already has an open PR adding ESM support. Ayo is not interested in "beating" Node.js in this way, but instead by fostering a more welcoming community and focusing on things Node.js has historically neglected. See #15 for the core values of Ayo.js.

**Comment by addaleax** [comment]
If I may add to that: It’s not that Node.js isn’t actively working on implementing this. If there turn out to be real shortcomings in Node’s implementation, then that’s certainly something worth discussing, but for now I agree with @TimothyGu and would say that focusing on this might not make the most sense.

**Comment by mearns** [comment]
fwiw, I've been discussing the Ayo fork with my team. One thing that came up was that it's hard to imagine Ayo gaining a lot of momentum in the broader (non-contributing) community without any technical impetus to switch. While I agree that "beating node" probably does not make a lot of sense as a specific goal of this project, I do wonder if having some technical leverage over node could help boost the Ayo project to increase it's chances of success. After all, forming a better model for community, moderation, and governance doesn't do a lot of good if the project flatlines and its community dissolves.

**Comment by italonascimento** [comment]
> After all, forming a better model for community, moderation, and governance doesn't do a lot of good if the project flatlines and its community dissolves

I guess a "better model for community, moderation, and governance" may be enough to make the project evolves really quickly, actually. That's why open source is so powerful, after all.

**Comment by Fishrock123** [comment]
Please see https://github.com/nodejs/node/pull/14369 - I suspect we'd be inclined to also adopt that (compatibility), but it would be useful to discuss shortcomings (which I would probably take and coordinate with Bradley and Node too).

ESM implications are far larger than just Ayo and I'm entrenched enough in it to want to not screw it up on all fronts if possible.

**Comment by ghost** [comment]
See also [What is the “module” package.json field for?](https://stackoverflow.com/questions/42708484/what-is-the-module-package-json-field-for/42817320#42817320) on SO for several additional links and some historical context.

**Comment by SteveCruise** [comment]
Thanks for answer, thank you thank you very much. A V8 member said es modules is ready to used.

**Comment by bmeck** [comment]
Let me know if any further questions on ESM exist.

**Comment by SteveCruise** [comment]
no
