### ISSUE TITLE
[q] Any plans for adding technically valuable features?

### ISSUE THREAD

**Issue by SkeLLLa** [ayojs/ayo#30]
Hello. Just to make it clear what is the purpose of this repo?

The tech feature in my meaning is something like rewriting http module to make it better, or just like adding http2, or module to support some protocol out-of-the-box like webrtc and so on, 

As far as I can see so far the most contributions are some sort of:
* choosing logos
* creating CoC and so on
* fixing typos in sources and documentation
* some codestyle fixes

So in order to make it clear and simplier to understand I'll divide the main question into a few:
1) Are thare any plans to backport technical features from main nodejs repo?
2) Are there any plans to add new tech features into this repo (if yes, will they go via PR into main repo)?
3) [if 2 is yes] What are those features?
4) Plans for some kind "stable" release ready for production?
or
5) Will this repo just be a nodejs fork (probably with changes from main repo) with politically correct CoC, Values and similar stuff?
6) Pros/Cons of ayo over nodejs. Why, for example, I should choose ayo over nodejs and will I have some cons by making such choise?

**Comment by anko** [comment]
This seems to be a subset of https://github.com/ayojs/ayo/issues/7. Perhaps you should comment there instead?

**Comment by Fishrock123** [comment]
1. See https://github.com/ayojs/ayo/issues/9 and https://github.com/ayojs/ayo/pull/22
2. General plans yes, I have some ideas but none 100% solid yet. They will be PR'd here. Node may or may not also adopt them.
3. again, _general_ plans, but see #18, #19, #21 etc for ideas
4. Yes, see discussion in https://github.com/ayojs/ayo/issues/16 - probably on less platforms for the mean time and certainly in no rush right now
5. see other answers
6. see other answers? That is pretty much impossible to say at this point, unless you are looking at contributing, in which case, here may be more friendly.

**Comment by nukeop** [comment]
don't hold your breath lmao

**Comment by varjmes** [comment]
The short answer is: yes! Things are evolving each day and I think Fishrock has covered some interesting things already.

So, please watch this space. Rome wasn't built in a day and we're building some great foundations right now so that the cool code and fly.
