### ISSUE TITLE
Temporary Lock on Repository

### ISSUE THREAD

**Issue by zkat** [ayojs/ayo#34]
Hey y'all.

You may have noticed that we've had some amount of really disruptive and unconstructive attention, largely from folks who aren't involved with either Ayo.js or Node.js.

Until this recent tide of attention dies down, I've set this repository to be collaborator-only as well as blocked any users with brand new accounts, since several people have made throwaways.

If you would like to collaborate on this project, please join the Discord channel and ask for access, we'll gladly hand it out! And, if you happen to try and abuse this process as well, be warned that you'll get the banhammer pretty quick. It is my hope that those who collaborate in this space do so in good faith: if you have issues that prevent you from doing that, I suggest you take your commentary to a different community.

**Comment by varjmes** [comment]
Repository is now open for all.
