### ISSUE TITLE
Proposal: Ayo.js members issue a joint non-discrimination statement

### ISSUE THREAD

**Issue by DelanoJ84** [ayojs/ayo#41]
Ayo.js should issue a statement assuring the community they will fairly investigate reported Code of Conduct violations regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation. No allowances will be made due to the aforementioned characteristics of the person making the report, the person being reported, or any people or groups mentioned in a report.

**Comment by benjamingr** [comment]
The code of conduct in Ayo (and Node.js) already states:

> In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.

I don't think that making a statement about enforcing it would matter that much, I think people will definitely judge Ayo based on how that policy is enforced.

**Comment by zkat** [comment]
I second @benjamingr's answer. We'll soon/eventually have a more formal/structured discussion about what changes to make to our CoC and enforcement process, but that list is only bound to get longer, and the enforcement process more specific, imo.
