### ISSUE TITLE
Volunteers needed for the core team!

### ISSUE THREAD

**Issue by varjmes** [ayojs/ayo#49]
Now that we have our [governance model](https://github.com/ayojs/ayo/blob/latest/GOVERNANCE.md) it is time to put together our core Ayo.js team.

# What's that then? 🤔 

As per our governance document:

> The core team is a team with the purpose of deciding the general direction of the project and managing cross-cutting concerns. They only decide over the most high-level aspects, all other matters should be delegated to another, more specific team.
>
> Every member of the core team is also an Owner of the ayojs GitHub organization.

The core team serves the interests of the Ayo.js project, suggesting ways in which to progress the project and overseeing things at a high level. Their job is not to have their hands in everything that happens within the project, but merely be aware and make sure we're achieving the general goal of Ayo. Each current and future working group (i.e not core) will be responsible for their own parts of Ayo. Core is a group to lean on when you're wondering "what next?" or "how can we achieve this?".

# How do I volunteer? 🙌 

Express your wish to be part of this team by commenting on this issue, saying as much. Please bare in mind that due to the small size of the project, we'll be asking a maximum of ~five people to come on board.

# I have questions ❓ 

To get the quickest response, please chat in our Discord: https://discord.gg/hCgptwH

**Comment by varjmes** [comment]
I nominate myself to be a member of the core team.

**Comment by ghost** [comment]
i nominate myself to be a member of the core team!

**Comment by zkat** [comment]
...And my axe!

_[edit by @zkat: I've withdrawn by nomination. See https://github.com/ayojs/ayo/issues/49#issuecomment-329002925 below]_

**Comment by sandfox** [comment]
I too nominate myself for core

**Comment by siddharthkp** [comment]
Hi 👋 

Would be happy to help!

**Comment by benjamingr** [comment]
Sorry for the question - but in Node.js terms would this be analogous to a collaborator or a TSC member?

**Comment by Fishrock123** [comment]
It would be analogous to TSC member, but the way it functions and the level of authority it has are still different.

**Comment by ghost** [comment]
@benjamingr it's more similar to a pre-convergence TSC member as in, there's inherently no technical association to the position

**Comment by Fishrock123** [comment]
That sounds like _pre-convergence_ (yay, confusing! 😞).

**Comment by ghost** [comment]
oh whoops, my bad haha

**Comment by benjamingr** [comment]
@Fishrock123 I would like to help but I can't commit to anything that would require continuous technical involvement due to time constraints.

**Comment by tortilla-reheat** [comment]
I volunteer! I have extensive technical experience on a few smaller projects, namely salsa-js and tortilla-js, which are real-world projects I think would be an asset here.

**Comment by Qard** [comment]
I, too, would be happy to help in any way I can. 💪

**Comment by addaleax** [comment]
I would like to nominate myself as well.

**Comment by zkat** [comment]
Hey all: I'm withdrawing my nomination 'cause I think I'd be more useful helping bootstrap the moderation team. When I think about it, any help that I could provide as a technical contributor can be done as a regular contributor and I don't really feel like there's much need to be in a core team or such -- I think my experiences with community stuff would be much more critical to have for moderation, at this stage. Once that's all in place, I might swap or something, but for the time being, I'll sit it out.

Note also: my most likely technical contribution for this project would be for a package management working group, and I would definitely help with that 👍

**Comment by abritinthebay** [comment]
I would like to nominate myself. Either way, I’m excited about this project.

**Comment by aqrln** [comment]
Hi 👋
I haven't been around recently due to the lack of time for open source, but I'm gradually coming back home to GitHub, and I'd be happy to help too!

**Comment by timilsinabishal** [comment]
I would like to nominate myself as well.

**Comment by zgagnon** [comment]
I would like to help out.

**Comment by Harrison-M** [comment]
I'd like to submit myself for nomination, if that's not presumptuous!

**Comment by TimothyGu** [comment]
I would like to nominate myself to the Core Team.

**Comment by slahiri** [comment]
I would like to help

**Comment by countnoobula** [comment]
Hey everyone! 😺🌷 

I mostly work in managing server end systems, but due to being genderfluid, I feel as if together, we can make Ayo what Node has failed to be.

I've helped my office a lot by creating a safe space where I can reach and help our family achieve our goals, and feel I can bring much the same safe space and motivation to the Ayo family! 🌹 

I volunteer! 😸

**Comment by frozzare** [comment]
I would also be interested to help! So I'm nominating myself to the core team.

**Comment by ghost** [comment]
thanks everyone for volunteering! we're going to close this issue and over the next days, the current founding members are coming up with a list of members for the teams! we'll update this issue once we've assembled that list.

**Comment by ghost** [comment]
the ayo core team consists of:
- @varjmes 
- @pup 
- @sandfox 
- @Qard 
- @addaleax 
- @aqrln 
- @Harrison-M 
- @TimothyGu 

we will create a discord role and channel, so everyone mentioned in here, please make sure to join our discord (link in the readme!)
