### ISSUE TITLE
Move non-essential C++ modules into addons?

### ISSUE THREAD

**Issue by brody2consult** [ayojs/ayo#50]
* ~~**Version**:~~
* ~~**Platform**:~~
* ~~**Subsystem**:~~

This would keep the core leaner and safer, though with the risk of increased divergence from "upstream" Node.js (especially with the modules moved out).

**Comment by Fishrock123** [comment]
Which parts do you see us moving out? I would imagine we'd lean more to adding more (though I am, myself, pretty hesitant about it) - addons can be problematic for many users with less than ideal setups.

Most things are quite important to running node itself, and the community has created me to rely heavily on the parts that aren't. As an example, we could remove `zlib` but I see more negatives in doing so than positives.

**Comment by brody2consult** [comment]
Especially crypto, HTTP server, TLS may not be useful for all users, especially desktop npm users and Android app embedders.

Or is it better to just start a new project based on V8 and libuv for this and #51?

**Comment by addaleax** [comment]
> Especially crypto, HTTP server, TLS may not be useful for all users, especially desktop npm users and Android app embedders.

`npm` users use `tls` extensively, namely for any download via https :) Also, if you really prefer not to have `tls` available, you can make custom builds using `--without-ssl`, but very few people use that.

**Comment by brody2consult** [comment]
Thanks guys for the responses to this and #51.
