### ISSUE TITLE
Expanding our CoC

### ISSUE THREAD

**Issue by notgne2** [ayojs/ayo#8]
Are there any plans to expand our CoC beyond the limiting bounds of the one currently linked to in Node.js? I would love to see some more hard work on our CoC, in order to make it larger and more specific to our needs as a new project with the community in mind.

**Comment by ghost** [comment]
i think that should be at a high priority once we form a governance structure... we definitely need clear enforcement guidelines and a moderation group

**Comment by hexafluoride** [comment]
🍆

**Comment by pup** [comment]
nevermind lmao

**Comment by varjmes** [comment]
I would definitely like to work on our COC. The one Node.js is insufficient, from an enforcement point of view. So I'd love to add some better enforcement steps. I helped write some, but I don't want to be biased to those. So if anyone has some examples of some enforcement processes, I'd love to hear them.

However, my ideas for enforcement are _not_ "one strike and you're out". That's ridiculous, quite frankly. Every case is different, and the community should be one where people aren't thrown out on a whim. It should, however, be a community where we take infractions seriously and deal with them appropriately.

**Comment by Fishrock123** [comment]
For context, the current (documented) CoC that the Node project uses is the [Contributor Covenant](https://www.contributor-covenant.org/) 1.4, which is (as I understand), [copied verbatim](https://github.com/nodejs/TSC/blob/e507a065ee508a1c27a7b78e3a77c6c262759eed/CODE_OF_CONDUCT.md).

**Comment by zkat** [comment]
tbh Node's CoC is pretty good, and it _does_ have some documented (if crappy) enforcement steps. More at issue is leadership that refuses to actually go through the motions of enforcement and prioritizes "peace" over doing their jobs lol

**Comment by zkat** [comment]
I'm going to close this, because it provides little context for constructive conversation and the CoC itself has been relatively uncontroversial.
