### ISSUE TITLE
First core team meeting!

### ISSUE THREAD

**Issue by addaleax** [ayojs/ayo#90]
Hi! I’d like to suggest that the @ayojs/core team holds a meeting in the near future. For at least me, @qard, @TimothyGu and @Fishrock123, I assume that would be best in the week of Oct 9 – 14 (since in the upcoming week Node Interactive takes place).

Question: Does anybody want to take the lead on this, organizing-wise? I guess right now that wouldn’t entail more than making a doodle + curating a list of agenda items. (I can act as a fallback but I think it would be nice to have somebody else on this – esp somebody who is not busy this week :))

If we want to follow Node’s example here, this would basically be a Hangout session + live streaming to Youtube (I *think* I got it figured out how to do that) + the possibility of interaction through the Discord and the Youtube chat. We don’t have to follow this, I am obviously pretty biased!

Sound ok? :)

**Comment by addaleax** [comment]
Btw, one thing I’d like to do differently than what Node does is to invite interested people into the hangout/whatever itself, as long as that still works wrt the number of people… what do you think?

**Comment by Qard** [comment]
👍 

Discord also has audio channels, so we might be able to have other people participate through there. 🤔

**Comment by Fishrock123** [comment]
Do keep in mind I am not on the "core" team. If invited, I would be willing to join so long as the meeting times are not overlapping with my existing schedule.

If we had more than hangouts-on-air supports (or if generally desired), I could stream to YouTube or twitch and we could use a discord channel for the meeting, similar for what I do for node.

**Comment by sandfox** [comment]
Happy to organise, I'm hopefully not to busy this week.
Before I make up a doodle, what timezone is everyone in? I'm GMT+1

**Comment by Harrison-M** [comment]
I think it's worth considering aiming for the 14th? If we aim for Saturday we might be able to get more participation across time zones. This is a bit selfish; if we meet during the week I'll have to get up early or keep y'all up late. I'm UTC-5 (CDT) right now.

**Comment by Qard** [comment]
Maybe we should add timezones to the contributor list. 🤔

I'm UTC-8, by the way.

**Comment by ghost** [comment]
i think hosting the meeting through discord is a good idea, since it also kind of filters questions from interested people (due to having to be in the server). we could use something like https://discordbots.org/bot/329331577467174919 to record audio and then later put it on youtube or soundcloud or something

**Comment by TimothyGu** [comment]
I'm in UTC-7. I usually have classes during the day, but happy to fill out a Doodle because my schedule isn't the same every day. Weekends and nights (preferably after 10pm) usually work.

**Comment by sandfox** [comment]
Quick thought RE: discord / youtube etc. Are we happy with only having voice? (I've no idea what everyones personal preferences are with regards to a video stream and wanting to see other people, or be seen).
FWIW I'm cool with either. Discord bot sounds good. and we should definately distribute audio etc afterwards.

Without wanting to be too formal, I think we should draw up some rough form of agenda (even if's just say hi to each other) and someone should probably be responsible for doing some minutes/summary as it would be good to make to make this as accessible as possible to other people, although we can probably do this afterwards as as we are going to record it.

I've got guestimate timezones for @varjmes (UTC+1) as I'm pretty sure you're somewhere in the same city as me! I still need some timezones for @addaleax @aqrln @pup and @Fishrock123 
(and anyone else who is going to be present)

From my brief look at timezones  and a map it seems that "morning north america /  afternoon europe" might be good option? (making some sweeping assumptions about peoples sleep patterns and general rhythms)

I've created a doodle here: https://doodle.com/poll/qvb2gkrny5nxpre4
it's public, using UTC time, and everyones vote is visible. I've broken the days down arbitrarily into ~4~ 2 hour blocks as I couldn't think of a better way to do it. I'm sorry it makes it look like a monster :-(

**Comment by addaleax** [comment]
Yeah, that’s what I was thinking hangouts – you can see pretty well who’s talking :) I haven’t ever done that with Discord so no idea how well that works there.

And I’m CEST (UTC + 2 until the end of October), but doodles should take care of timezones pretty well if we make sure there’s a sufficiently wide range of options :)

**Comment by varjmes** [comment]
I look forward to this!

I'd offer to organise but I've been absent from ayo for the past two weeks due to exhaustion/illness/disability so I need to catch up before I can commit to organising.

I'm BST (GMT + 1) right now.

**Comment by Fishrock123** [comment]
I am in pacific time currently (GMT -7?). I've entered my time into the doodle.

**Comment by sandfox** [comment]
Thanks everyone who's doodled so far. At a glance it's looking like either wednesday, thursday, friday at 8-10pm ( 20-22hrs) is a potential winner.

**Comment by scotttrinh** [comment]
@sandfox 8-10pm UTC?

**Comment by sandfox** [comment]
@scotttrinh woops, forgot that very crucial bit of info, yes UTC!

**Comment by ghost** [comment]
oh yeah by the way i can totally try to organize this meeting!

**Comment by sandfox** [comment]
Ok, we have scheduling conflicts, or at least a consensus problem 😄 , there isn't a time where all of us are available at the same time. Unless some/all us are capable of being free at some new time I guess some of us aren't going to be able to make it... (or we do it twice-ish? no idea how that would work).

I dislike the the idea of going with when the most people are free because that feels a little disenfranchasing, but I'm not sure what better/other options there are?

**Comment by scotttrinh** [comment]
My attendance is totally not necessary, so feel free to choose a time that conflicts with my schedule, if that helps us find a good time. I am mostly interested in listening in, which I can do after the fact.

**Comment by addaleax** [comment]
@sandfox Do you maybe just want to make a decision and pick a (any) time? I think that might be the most helpful right now…

**Comment by sandfox** [comment]
yep @addaleax I think this might be the best course of action.

I'm going to _omminously_ choose friday 13th 21:00-23:00 UTC as the rought time slot. This seems to include most of us except @Harrison-M for sure and maybe @varjmes. How do you feel about this?

I'm also going to say how does 21:00 as a start time sound to everyone? I think we probably have a bit of wiggle room (30 mins to an hour) on that. 

As for software/tool we've got the option of zoom, hangouts (+youtube), discord, or whatever anyone else can think up. As @Fishrock123 suggested, doing a hangout with streaming to youtube seems like a cool idea, and then we could take question etc via discord.

**Comment by TimothyGu** [comment]
21:00 UTC on Friday sounds good to me.

**Comment by Fishrock123** [comment]
> As @fishrock123 suggested, doing a hangout with streaming to youtube seems like a cool idea, and then we could take question etc via discord.

Slight clarification: I can stream/record it regardless what meeting/voice software is used for the meeting.

If that is desired someone will need to set me up on an ayo youtube channel, or I suppose I could just use my own channel.

21:00 UTC on Friday is fine here.

**Comment by sandfox** [comment]
gotcha @Fishrock123 . Having recently tried doing a bunch of hangouts at work with about 8-12 people across a few continents  and having everyone's laptops fans screaming at max rpm, I'm inclined to suggest trying zoom, it's been reasonably not rubbish for us and I've seen it work on linux, and I also have a license so the meeting can extend as long as we want (https://zoom.us/download )

We also don't have an ayojs youtube channel yet and I can't work out how to make one on youtube... We could always use twitch, but I think that might not as accessible as youtube?

**Comment by sandfox** [comment]
I've posted a link to the meeting in the discord core team chat

**Comment by sandfox** [comment]
@pup has made a specific issue (that resolves this issue?) here: https://github.com/ayojs/ayo/issues/105

**Comment by Fishrock123** [comment]
Argh, did this happen? Sorry I forgot to add it to my calendar :(

**Comment by sandfox** [comment]
hehe, yeah it @Fishrock123 but no worries. We recorded the audio and will put it along with the minutes in #105  (once I find time and remember how to transcode it.)
