### ISSUE TITLE
contributing.md changes that we may want to backport

### ISSUE THREAD

**Issue by addaleax** [ayojs/ayo#96]
https://github.com/nodejs/node/commit/5be4dfaa13b0 & https://github.com/nodejs/node/commit/3f1cca481765 changed text in the `CONTRIBUTING.md` file, which might be worth including in our own files but which didn’t apply cleanly.

@srilq Do you want to take a look at this?

**Comment by stefee** [comment]
@addaleax Sure! :^)

Do you have any specific concerns with how this applies or is it purely a formatting issue? I'll give the content a check-over too but my understanding of it is limited.

**Comment by ghost** [comment]
@addaleax did you merge in the rest of the changes in 5be4dfa?

@srilq the content from the first commit applies to us too, so there's no need to modify anything other than just copying it in

**Comment by addaleax** [comment]
@srilq Tbh, I didn’t really take a look at it – I just wanted the backport from upstream to work so I skipped that part of the commit :sweat_smile: 

@pup Yup, the rest of those changes are merged, everything except `CONTRIBUTING.md` :)
